### ISSUE TITLE
Looking for the Mobitex Interface Specification

### ISSUE THREAD

**Issue by datafl4sh** [IanWraith/MobyMon#1]
Hello,

I took a look at your code and I noticed that it is capable of decoding a great part of the ROSI frames (SVP, FRI and so on). I am looking for the documentation of the Mobitex ROSI layer and I wonder if you have it and you are willing to share it. Unfortunately ,the Mobitex air interface is not documented in the open version of the Mobitex Interface Specification and the website `mobitex.com` disappeared from the Internet, so I am unable to acquire it from official channels.

Thank you!

**Comment by IanWraith** [comment]
Hello
         Sorry but I last worked on MobyMon back in the late 90s. I had a fair amount of documentation for various parts of Mobitex on paper which I had been given. However it took up a fair amount of space and I'm afraid it was all put out for paper recycling when I moved house around 15 years as I never thought it would be needed again.

Sorry about that but good luck finding this info somewhere.

Regards

Ian
